name: Continous Integration

on:
  push:
    branches:
      - main
      - testbranch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install

      - name: Pruebas
        run: |
          npm run test
